apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: rabbitmq-demo
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: rabbitmq_demo/service1:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: Service2Uri
          value: "http://service2:80"
        - name: Service3Uri
          value: "http://service3:80"
        envFrom:
        - configMapRef:
            name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: rabbitmq-demo
  labels:
    app: service1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: service1
